/*
 * Catalogue des spécialités médicales proposées à l'admin.
 *
 * Ce n'est PAS le référentiel : celui-ci vit dans la table `specialites` et
 * ne contient que ce que l'admin a réellement ouvert sur la plateforme. Cette
 * liste-ci est une aide à la saisie — l'écran /espace-admin/parametres la
 * propose en suggestions, en retirant au passage ce qui est déjà référencé,
 * et laisse toujours la possibilité de taper autre chose.
 *
 * Couvre les spécialités et professions de santé courantes en Guinée et dans
 * l'espace francophone, y compris les plateaux techniques (laboratoire,
 * imagerie) qui ne sont pas des spécialités médicales au sens strict mais
 * que les patients cherchent de la même manière.
 */

export const CATALOGUE_SPECIALITES: string[] = [
  "Acupuncture",
  "Addictologie",
  "Allergologie",
  "Anatomopathologie",
  "Andrologie",
  "Anesthésie-réanimation",
  "Angiologie",
  "Audioprothèse",
  "Cardiologie",
  "Chirurgie cardiaque",
  "Chirurgie dentaire",
  "Chirurgie digestive",
  "Chirurgie esthétique",
  "Chirurgie générale",
  "Chirurgie infantile",
  "Chirurgie maxillo-faciale",
  "Chirurgie orthopédique",
  "Chirurgie plastique",
  "Chirurgie thoracique",
  "Chirurgie urologique",
  "Chirurgie vasculaire",
  "Dentaire",
  "Dermatologie",
  "Diabétologie",
  "Diététique",
  "Échographie",
  "Endocrinologie",
  "Endoscopie digestive",
  "Épidémiologie",
  "Ergothérapie",
  "Gastro-entérologie",
  "Génétique médicale",
  "Gériatrie",
  "Gynécologie",
  "Gynécologie-obstétrique",
  "Hématologie",
  "Hépatologie",
  "Hygiène hospitalière",
  "Immunologie",
  "Implantologie dentaire",
  "Imagerie médicale",
  "Infectiologie",
  "Infirmerie",
  "Kinésithérapie",
  "Laboratoire d'analyses",
  "Maïeutique (sage-femme)",
  "Mammographie",
  "Médecine du sport",
  "Médecine du travail",
  "Médecine esthétique",
  "Médecine générale",
  "Médecine interne",
  "Médecine légale",
  "Médecine nucléaire",
  "Médecine physique et réadaptation",
  "Médecine tropicale",
  "Microbiologie",
  "Néonatologie",
  "Néphrologie",
  "Neurochirurgie",
  "Neurologie",
  "Nutrition",
  "Odontologie",
  "Oncologie",
  "Oncologie pédiatrique",
  "Ophtalmologie",
  "Optométrie",
  "ORL",
  "Orthodontie",
  "Orthopédie",
  "Orthophonie",
  "Orthoptie",
  "Ostéopathie",
  "Parasitologie",
  "Parodontologie",
  "Pédiatrie",
  "Pédopsychiatrie",
  "Pédicure-podologie",
  "Pharmacie",
  "Phlébologie",
  "Planning familial",
  "Pneumologie",
  "Podologie",
  "Proctologie",
  "Prothèses et appareillage",
  "Psychiatrie",
  "Psychologie",
  "Radiologie",
  "Radiothérapie",
  "Réanimation",
  "Rééducation fonctionnelle",
  "Rhumatologie",
  "Sage-femme",
  "Santé publique",
  "Scanner et IRM",
  "Sexologie",
  "Soins infirmiers",
  "Soins palliatifs",
  "Stomatologie",
  "Toxicologie",
  "Transfusion sanguine",
  "Traumatologie",
  "Urgences",
  "Urologie",
  "Vaccination",
  "Virologie",
];
