-- ============================================================
-- 0025 — Référentiel des spécialités pratiquées en Guinée
--
--   La table `specialites` n'était remplie que par le seed de démarrage :
--   huit entrées, à charge pour l'administrateur d'ajouter le reste une par
--   une. La plateforme livre désormais le référentiel réel — des CHU de
--   Conakry aux cabinets privés et centres de santé.
--
--   Ce qui ne se pratique pas en Guinée en est écarté (radiothérapie,
--   chirurgie cardiaque, médecine nucléaire, génétique médicale) : proposer
--   une spécialité qui n'existe pas enverrait le patient vers une page de
--   résultats qui ne se remplira jamais. L'administrateur peut l'ajouter
--   le jour où un service ouvre.
--
--   Les icônes sont celles que `lib/icones-specialites` déduit du nom :
--   la base et l'affichage disent la même chose, même si la déduction
--   côté application resterait de toute façon le filet de sécurité.
--
--   Rejouable : les noms déjà présents ne sont pas touchés, et les lignes
--   dont l'icône est restée nulle (celles ajoutées avant cette migration)
--   sont complétées au passage.
-- ============================================================

insert into specialites (nom, emoji) values
  ('Médecine générale', '🩺'),
  ('Médecine interne', '🧑‍⚕️'),
  ('Pédiatrie', '👶'),
  ('Néonatologie', '👶'),
  ('Gynécologie', '🌸'),
  ('Sage-femme', '🤰'),
  ('Planning familial', '🌸'),
  ('Cardiologie', '❤️'),
  ('Dermatologie', '🧴'),
  ('Ophtalmologie', '👁️'),
  ('Optométrie', '👓'),
  ('ORL', '👂'),
  ('Audioprothèse', '🦻'),
  ('Dentaire', '🦷'),
  ('Orthodontie', '🦷'),
  ('Chirurgie maxillo-faciale', '🔪'),
  ('Neurologie', '🧠'),
  ('Neurochirurgie', '🧠'),
  ('Psychiatrie', '💭'),
  ('Psychologie', '💭'),
  ('Addictologie', '💭'),
  ('Pneumologie', '🫁'),
  ('Gastro-entérologie', '🫃'),
  ('Hépatologie', '🫃'),
  ('Néphrologie', '🫘'),
  ('Dialyse', '🫘'),
  ('Urologie', '🫘'),
  ('Andrologie', '♂️'),
  ('Endocrinologie', '🍬'),
  ('Diabétologie', '🍬'),
  ('Nutrition', '🥗'),
  ('Diététique', '🥗'),
  ('Rhumatologie', '🦴'),
  ('Orthopédie', '🦴'),
  ('Traumatologie', '🦴'),
  ('Chirurgie générale', '🔪'),
  ('Chirurgie infantile', '🔪'),
  ('Chirurgie plastique', '🔪'),
  ('Chirurgie vasculaire', '🔪'),
  ('Anesthésie-réanimation', '🫀'),
  ('Réanimation', '🫀'),
  ('Urgences', '🚑'),
  ('Radiologie', '🩻'),
  ('Échographie', '🩻'),
  ('Laboratoire', '🧪'),
  ('Biologie médicale', '🧪'),
  ('Anatomopathologie', '🔬'),
  ('Microbiologie', '🔬'),
  ('Parasitologie', '🦠'),
  ('Hématologie', '🩸'),
  ('Transfusion sanguine', '🩸'),
  ('Infectiologie', '🦠'),
  ('Virologie', '🦠'),
  ('Immunologie', '🛡️'),
  ('Allergologie', '🤧'),
  ('Oncologie', '🎗️'),
  ('Gériatrie', '🧓'),
  ('Médecine du travail', '👷'),
  ('Médecine légale', '⚖️'),
  ('Médecine tropicale', '🌴'),
  ('Médecine du sport', '🏃'),
  ('Santé publique', '📊'),
  ('Épidémiologie', '📈'),
  ('Vaccination', '💉'),
  ('Dépistage', '🧫'),
  ('Pharmacie', '💊'),
  ('Kinésithérapie', '💪'),
  ('Rééducation fonctionnelle', '💪'),
  ('Ergothérapie', '🤲'),
  ('Orthophonie', '🗣️'),
  ('Podologie', '🦶'),
  ('Prothèses et appareillage', '🦿'),
  ('Soins infirmiers', '💉'),
  ('Soins palliatifs', '🕊️'),
  ('Médecine traditionnelle', '🌿'),
  ('Toxicologie', '☠️')
on conflict (nom) do nothing;

-- Lignes anciennes laissées sans icône : on leur donne celle du référentiel.
update specialites s
   set emoji = r.emoji
  from (values
  ('Médecine générale', '🩺'),
  ('Médecine interne', '🧑‍⚕️'),
  ('Pédiatrie', '👶'),
  ('Néonatologie', '👶'),
  ('Gynécologie', '🌸'),
  ('Sage-femme', '🤰'),
  ('Planning familial', '🌸'),
  ('Cardiologie', '❤️'),
  ('Dermatologie', '🧴'),
  ('Ophtalmologie', '👁️'),
  ('Optométrie', '👓'),
  ('ORL', '👂'),
  ('Audioprothèse', '🦻'),
  ('Dentaire', '🦷'),
  ('Orthodontie', '🦷'),
  ('Chirurgie maxillo-faciale', '🔪'),
  ('Neurologie', '🧠'),
  ('Neurochirurgie', '🧠'),
  ('Psychiatrie', '💭'),
  ('Psychologie', '💭'),
  ('Addictologie', '💭'),
  ('Pneumologie', '🫁'),
  ('Gastro-entérologie', '🫃'),
  ('Hépatologie', '🫃'),
  ('Néphrologie', '🫘'),
  ('Dialyse', '🫘'),
  ('Urologie', '🫘'),
  ('Andrologie', '♂️'),
  ('Endocrinologie', '🍬'),
  ('Diabétologie', '🍬'),
  ('Nutrition', '🥗'),
  ('Diététique', '🥗'),
  ('Rhumatologie', '🦴'),
  ('Orthopédie', '🦴'),
  ('Traumatologie', '🦴'),
  ('Chirurgie générale', '🔪'),
  ('Chirurgie infantile', '🔪'),
  ('Chirurgie plastique', '🔪'),
  ('Chirurgie vasculaire', '🔪'),
  ('Anesthésie-réanimation', '🫀'),
  ('Réanimation', '🫀'),
  ('Urgences', '🚑'),
  ('Radiologie', '🩻'),
  ('Échographie', '🩻'),
  ('Laboratoire', '🧪'),
  ('Biologie médicale', '🧪'),
  ('Anatomopathologie', '🔬'),
  ('Microbiologie', '🔬'),
  ('Parasitologie', '🦠'),
  ('Hématologie', '🩸'),
  ('Transfusion sanguine', '🩸'),
  ('Infectiologie', '🦠'),
  ('Virologie', '🦠'),
  ('Immunologie', '🛡️'),
  ('Allergologie', '🤧'),
  ('Oncologie', '🎗️'),
  ('Gériatrie', '🧓'),
  ('Médecine du travail', '👷'),
  ('Médecine légale', '⚖️'),
  ('Médecine tropicale', '🌴'),
  ('Médecine du sport', '🏃'),
  ('Santé publique', '📊'),
  ('Épidémiologie', '📈'),
  ('Vaccination', '💉'),
  ('Dépistage', '🧫'),
  ('Pharmacie', '💊'),
  ('Kinésithérapie', '💪'),
  ('Rééducation fonctionnelle', '💪'),
  ('Ergothérapie', '🤲'),
  ('Orthophonie', '🗣️'),
  ('Podologie', '🦶'),
  ('Prothèses et appareillage', '🦿'),
  ('Soins infirmiers', '💉'),
  ('Soins palliatifs', '🕊️'),
  ('Médecine traditionnelle', '🌿'),
  ('Toxicologie', '☠️')
  ) as r (nom, emoji)
 where s.nom = r.nom
   and s.emoji is null;
